myweb/myflask/accounts/urls.py
#!/usr/bin/env python3
# -*- coding: utf-8 -*-

from flask import Blueprint
from . import views

accounts = Blueprint("accounts", __name__)

accounts.add_url_rule("/login", "login", views.login, methods=["POST", "GET"])
accounts.add_url_rule("/register", "register", views.register, methods=["POST", "GET"])
accounts.add_url_rule("/logout", "logout", views.logout)

myweb/myflask/main/urls.py
#!/usr/bin/env python3
#-*- coding: utf-8 -*-
"""
路由
"""

from flask import Blueprint, g

from . import views

main = Blueprint('main', __name__)

main.add_url_rule("/", "index", views.index)
main.add_url_rule("/sms_table", "sms", view_func=views.all_data)
main.add_url_rule('/hello/<username>', "hello", view_func=views.hello, methods=['POST', 'GET'])
main.add_url_rule('/hello', view_func=views.hello, methods=['POST', 'GET'])
main.add_url_rule('/test1', "test1", views.test1)
# main.add_url_rule('/login', view_func=views.login, methods=['GET', "POST"])
############ cur post 请求格式
# 传 json  {'mobile': ""， "content" : "**$$**$$***$$***$$***"}
# curl -i -H "Content-Type: application/json" -X POST -d '{"mobile" : "19994411399", "content" : "13.231.45.60$$Geth-test02$$erc20API$$2019-10-15 12:55:12$$出错重启了一次"}' http://localhost:5000/monitor/sms
main.add_url_rule('/monitor/sms', "sms_send", views.send_sms, methods=['POST'])

main.add_url_rule('/back/server_info', view_func=views.server_info)
main.add_url_rule('/back/home', view_func=views.back_home)
main.add_url_rule('/back/server_add', view_func=views.server_add, methods=['GET', 'POST'])

main.add_url_rule('/post', "post_test", views.post_test, methods=['POST', 'GET'])

# main.before_app_request(views.before_app_request)
# # main.after_app_request(views.after_app_requst)

myweb/myflask/accounts/models.py
#!/usr/bin/env python3
#-*- coding: utf-8 -*-

from flask_login import UserMixin

class User(UserMixin):
    pass

myweb/myflask/accounts/views.py
#!/usr/bin/env python3
# -*- coding: utf-8 -*-

from flask import url_for, redirect, request, render_template, flash
from flask_login import login_user, logout_user, login_required
from app import login_manager
from .models import User

# 用户记录表
users = [
    {'username': 'Tom', 'password': '111111'},
    {'username': 'Bob', 'password': '123456'},
]

#### 用户验证
# 实验，用一个 dict 记录用户
# 通过用户名查询用户记录，如果不存在，返回None
def query_user(username):
    for user in users:
        if user['username'] == username:
            return user

# 如果用户存在，构建一个新的用户类对象，并使用用户名作为ID
# 如果不存在，必须返回None
@login_manager.user_loader
def load_user(username):
    if query_user(username) is not None:
        curr_user = User()
        curr_user.id = username
        return curr_user

# 从请求参数中获取用户名
@login_manager.request_loader
def load_user_from_request(requtest):
    username = request.args.get('username')
    if query_user(username) is not None:
        curr_user = User()
        curr_user.id = username
        return curr_user

# 用户登录
def login():
    print("next: ", request.args.get('next'))
    if request.method == 'POST':
        username = request.form.get('username')
        print(">>>>>>>>>>>>>>>>>>>>>>>>>>", username, " + ", request.form['password'])
        user = query_user(username)
        # 验证用户名及密码
        if user is not None and user['password'] == request.form['password']:
            curr_user = User()
            curr_user.id = username

            # 通过 Flask-Login的login_user方法登录用户
            login_user(curr_user)

            # 如果请求中有next返回上一页，没有就返回index
            next = request.args.get('next')
            return redirect(next or url_for("main.back_home"))

        flash("Wrong username or password")
    # GET请求
    return render_template("accounts/signin.html")

# 注销用户
@login_required
def logout():
    # 调用系统方法注销用户
    logout_user()
    return redirect("/")

# 用户注册
def register():
    if request.method == "POST":
        flash("注册成功")
        return redirect("accounts.login")
    return render_template("accounts/signup.html")

myweb/myflask/templates/accounts/login.html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">
<title>用户登录</title>

<link rel="stylesheet" href="/static/css/lg-style.css" />

<body>

<div class="login-container">
	<h1>用户登录</h1>

	<!-- <div class="connect">
		<p>www.17sucai.com</p>
	</div> -->

	<form action="" method="post" id="loginForm">
		<div>
			<input type="text" name="username" class="username" placeholder="用户名" autocomplete="off"/>
		</div>
		<div>
			<input type="password" name="password" class="password" placeholder="密码" oncontextmenu="return false" onpaste="return false" />
        </div>
        {% with message = get_flashed_messages() %}
            <div>{{ message[0] }}</div>
        {% endwith %}
		<button id="submit" type="submit">登 陆</button>
	</form>

	<!-- <a href="register.html"> -->
	<a href="{{ url_for('accounts.register') }}">
		<button type="button" class="register-tis">还有没有账号？</button>
	</a>

</div>

<script src="/static/js/lg-jquery.min.js"></script>
<script src="/static/js/lg-common.js"></script>
<!--背景图片自动更换-->
<script src="/static/js/lg-supersized.3.2.7.min.js"></script>
<script src="/static/js/lg-supersized-init.js"></script>
<!--表单验证-->
<script src="/static/js/lg-jquery.validate.min.js?var1.14.0"></script>

</body>
</html>

myweb/myflask/templates/accounts/logout.html
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8"> 
	<title>Bootstrap 实例 - 模态框（Modal）插件</title>
	<link rel="stylesheet" href="https://cdn.staticfile.org/twitter-bootstrap/3.3.7/css/bootstrap.min.css">
	<script src="https://cdn.staticfile.org/jquery/2.1.1/jquery.min.js"></script>
	<script src="https://cdn.staticfile.org/twitter-bootstrap/3.3.7/js/bootstrap.min.js"></script>
</head>
<body>

<h2>创建模态框（Modal）</h2>
<!-- 按钮触发模态框 -->
<button class="btn btn-primary btn-lg" data-toggle="modal" data-target="#myModal">
	开始演示模态框
</button>
<!-- 模态框（Modal） -->
<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
	<div class="modal-dialog">
		<div class="modal-content">
			<div class="modal-header">
				<button type="button" class="close" data-dismiss="modal" aria-hidden="true">
					&times;
				</button>
				<h4 class="modal-title" id="myModalLabel">
					模态框（Modal）标题
				</h4>
			</div>
			<div class="modal-body">
				在这里添加一些文本
			</div>
			<div class="modal-footer">
				<button type="button" class="btn btn-default" data-dismiss="modal">关闭
				</button>
				<button type="button" class="btn btn-primary">
					提交更改
				</button>
			</div>
		</div><!-- /.modal-content -->
	</div><!-- /.modal -->
</div>
</body>
</html>

myweb/myflask/templates/accounts/popupsignin.html
<!doctype html>
<html  lang="en">

    <head>
        <!-- meta data -->
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->

        <!--font-family-->
		<link href="https://fonts.googleapis.com/css?family=Poppins:100,200,300,400,500,600,700,800,900&amp;subset=devanagari,latin-ext" rel="stylesheet">
        
        <!-- title of site -->
        <title>Sign in</title>

        <!-- For favicon png -->
		<link rel="shortcut icon" type="image/icon" href="assets/logo/favicon.png"/>
       
        <!--font-awesome.min.css-->
        <link rel="stylesheet" href="assets/css/font-awesome.min.css">
		
		<!--animate.css-->
        <link rel="stylesheet" href="assets/css/animate.css">
		
        <!--bootstrap.min.css-->
        <link rel="stylesheet" href="assets/css/bootstrap.min.css">
		
		<!-- bootsnav -->
		<link rel="stylesheet" href="assets/css/bootsnav.css" >	
        
        <!--style.css-->
        <link rel="stylesheet" href="assets/css/style.css">
        
        <!--responsive.css-->
        <link rel="stylesheet" href="assets/css/responsive.css">
        
        <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
        <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
		
        <!--[if lt IE 9]>
			<script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
			<script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
        <![endif]-->

    </head>
	
	<body>
		<!--[if lte IE 9]>
            <p class="browserupgrade">You are using an <strong>outdated</strong> browser. Please <a href="https://browsehappy.com/">upgrade your browser</a> to improve your experience and security.</p>
        <![endif]-->
		
		<!-- signin end -->
		<section class="signin popup-in">
			<div class="container">

				<div class="sign-content popup-in-content">
					<div class="popup-in-txt">
						<h2>sign in</h2>
						
						<div class="row">
							<div class="col-sm-12">
								<div class="signin-form">
									<form action="signin.html">
										<div class="form-group">
										    <label for="signin_form">Email</label>
										    <input type="email" class="form-control" id="signin_form" placeholder="enter your email here">
										</div><!--/.form-group -->
										<div class="form-group">
											<label for="signin_form">password</label>
										    <input type="password" class="form-control" id="signin_form" placeholder="Password">
										</div><!--/.form-group -->
									</form><!--/form -->
								</div><!--/.signin-form -->
							</div><!--/.col -->
						</div><!--/.row -->
						
						<div class="row">
							<div class="col-sm-12">
								<div class="signin-password">
									<div class="awesome-checkbox-list">
										<ul class="unstyled centered">

											<li>
											    <input class="styled-checkbox" id="styled-checkbox-2" type="checkbox" value="value2">
											    <label for="styled-checkbox-2">remember password</label>
											</li>

											<li>
											    <a href="#">Forgot email or password ?</a>
											</li>

										</ul>
									</div><!--/.awesome-checkbox-list -->
								</div><!--/.signin-password -->
							</div><!--/.col -->
						</div><!--/.row -->

						<div class="row">
							<div class="col-sm-12">
								<div class="signin-footer">
									<button type="button" class="btn signin_btn">
									sign in
									</button>
									<p>
										Don’t have an Account ?
										<a href="signup.html">register</a>
									</p>
								</div><!--/.signin-footer -->
							</div><!--/.col-->
						</div><!--/.row -->
					</div><!-- .popup-in-txt -->
				</div><!--/.sign-content -->
			</div><!--/.container -->

		</section><!--/.signin -->
		
		<!-- signin end -->

		<!--footer copyright start -->
		<footer class="footer-copyright">
			<div id="scroll-Top">
				<i class="fa fa-angle-double-up return-to-top" id="scroll-top" data-toggle="tooltip" data-placement="top" title="" data-original-title="Back to Top" aria-hidden="true"></i>
			</div><!--/.scroll-Top-->

		</footer><!--/.hm-footer-copyright-->
		<!--footer copyright  end -->


		 <!-- Include all js compiled plugins (below), or include individual files as needed -->

		<script src="assets/js/jquery.js"></script>
        
        <!--modernizr.min.js-->
        <script src="https://cdnjs.cloudflare.com/ajax/libs/modernizr/2.8.3/modernizr.min.js"></script>
		
		<!--bootstrap.min.js-->
        <script src="assets/js/bootstrap.min.js"></script>
		
		<!-- bootsnav js -->
		<script src="assets/js/bootsnav.js"></script>
		
		<!-- jquery.sticky.js -->
		<script src="assets/js/jquery.sticky.js"></script>
		<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-easing/1.4.1/jquery.easing.min.js"></script>
		
        
        <!--Custom JS-->
        <script src="assets/js/custom.js"></script>

    </body>
	
</html>

myweb/myflask/templates/accounts/popupsignup.html
<!doctype html>
<html  lang="en">

    <head>
        <!-- meta data -->
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->

        <!--font-family-->
		<link href="https://fonts.googleapis.com/css?family=Poppins:100,200,300,400,500,600,700,800,900&amp;subset=devanagari,latin-ext" rel="stylesheet">
        
        <!-- title of site -->
        <title>Sign up</title>

        <!-- For favicon png -->
		<link rel="shortcut icon" type="image/icon" href="assets/logo/favicon.png"/>
       
        <!--font-awesome.min.css-->
        <link rel="stylesheet" href="assets/css/font-awesome.min.css">
		
		<!--animate.css-->
        <link rel="stylesheet" href="assets/css/animate.css">
		
        <!--bootstrap.min.css-->
        <link rel="stylesheet" href="assets/css/bootstrap.min.css">
		
		<!-- bootsnav -->
		<link rel="stylesheet" href="assets/css/bootsnav.css" >	
        
        <!--style.css-->
        <link rel="stylesheet" href="assets/css/style.css">
        
        <!--responsive.css-->
        <link rel="stylesheet" href="assets/css/responsive.css">
        
        <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
        <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
		
        <!--[if lt IE 9]>
			<script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
			<script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
        <![endif]-->

    </head>
	
	<body>
		<!--[if lte IE 9]>
            <p class="browserupgrade">You are using an <strong>outdated</strong> browser. Please <a href="https://browsehappy.com/">upgrade your browser</a> to improve your experience and security.</p>
        <![endif]-->
		
		<!-- signin end -->
		<section class="signin signup popup-up">
			<div class="container">

				<div class="sign-content popup-in-content">
					<div class="popup-in-txt">
						<h2>sign up</h2>
						
						<div class="row">
							<div class="col-sm-12">
								<div class="signin-form">
									<form action="signin.html">
										<div class="form-col">
											<div class="form-group">
											    <label for="signin_form">first name</label>
											    <input type="text" class="form-control" id="signin_form" placeholder="first name">
											</div><!--/.form-group -->
										</div><!--/.form-col -->
										<div class="form-col1">
											<div class="form-group">
												<label for="signin_form">last name</label>
											    <input type="text" class="form-control" id="signin_form" placeholder="last name">
											</div><!--/.form-group -->
										</div><!--/.form-col1 -->
										<div class="form-group">
											<label for="signin_form">Email</label>
										    <input type="email" class="form-control" id="signin_form" placeholder="enter your email here">
										</div><!--/.form-group -->
										<div class="form-group">
											<label for="signin_form">password</label>
										    <input type="password" class="form-control" id="signin_form" placeholder="Password">
										</div><!--/.form-group -->
										<div class="form-group">
											<label for="signin_form">retype password</label>
										    <input type="password" class="form-control" id="signin_form" placeholder="Retype Password">
										</div><!--/.form-group -->
									</form><!--/form -->
								</div><!--/.signin-form -->
							</div><!--/.col -->
						</div><!--/.row -->
						
						<div class="row">
							<div class="col-sm-12">
								<div class="signin-password">
									<div class="awesome-checkbox-list">
										<ul class="unstyled centered">

											<li>
											    <input class="styled-checkbox" id="styled-checkbox-2" type="checkbox" value="value2">
											    <label for="styled-checkbox-2">accept our terms & condition</label>
											</li>

											<li></li>

										</ul>
									</div><!--/.awesome-checkbox-list -->
								</div><!--/.signin-password -->
							</div><!--/.col -->
						</div><!--/.row -->


						<div class="row">
							<div class="col-sm-12">
								<div class="signin-footer">
									<button type="button" class="btn signin_btn">
									sign up
									</button>
									<p>
										already member ?
										<a href="signin.html">sign in</a>
									</p>
								</div><!--/.signin-footer -->
							</div><!--/.col-->
						</div><!--/.row -->
					</div><!-- .popup-in-txt -->
				</div><!--/.sign-content -->
			</div><!--/.container -->

		</section><!--/.signin -->
		
		<!-- signin end -->

		<!--footer copyright start -->
		<footer class="footer-copyright">
			<div id="scroll-Top">
				<i class="fa fa-angle-double-up return-to-top" id="scroll-top" data-toggle="tooltip" data-placement="top" title="" data-original-title="Back to Top" aria-hidden="true"></i>
			</div><!--/.scroll-Top-->

		</footer><!--/.hm-footer-copyright-->
		<!--footer copyright  end -->


		 <!-- Include all js compiled plugins (below), or include individual files as needed -->

		<script src="assets/js/jquery.js"></script>
        
        <!--modernizr.min.js-->
        <script src="https://cdnjs.cloudflare.com/ajax/libs/modernizr/2.8.3/modernizr.min.js"></script>
		
		<!--bootstrap.min.js-->
        <script src="assets/js/bootstrap.min.js"></script>
		
		<!-- bootsnav js -->
		<script src="assets/js/bootsnav.js"></script>
		
		<!-- jquery.sticky.js -->
		<script src="assets/js/jquery.sticky.js"></script>
		<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-easing/1.4.1/jquery.easing.min.js"></script>
		
        
        <!--Custom JS-->
        <script src="assets/js/custom.js"></script>

    </body>
	
</html>

myweb/myflask/templates/accounts/register.html
<!DOCTYPE html
	PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">

<head>
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
	<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">
	<title>注册</title>
	<link rel="stylesheet" href="/static/css/lg-style.css" />

<body>

	<div class="register-container">
		<h1>ShareLink</h1>

		<div class="connect">
			<p>Link the world. Share to world.</p>
		</div>

		<form action="" method="post" id="registerForm">
			<div>
				<input type="text" name="username" class="username" placeholder="您的用户名" autocomplete="off" />
			</div>
			<div>
				<input type="password" name="password" class="password" placeholder="输入密码" oncontextmenu="return false"
					onpaste="return false" />
			</div>
			<div>
				<input type="password" name="confirm_password" class="confirm_password" placeholder="再次输入密码"
					oncontextmenu="return false" onpaste="return false" />
			</div>
			<div>
				<input type="text" name="phone_number" class="phone_number" placeholder="输入手机号码" autocomplete="off"
					id="number" />
			</div>
			<div>
				<input type="email" name="email" class="email" placeholder="输入邮箱地址" oncontextmenu="return false"
					onpaste="return false" />
			</div>

			<button id="submit" type="submit">注 册</button>
		</form>
		<a href="index.html">
			<button type="button" class="register-tis">已经有账号？</button>
		</a>

	</div>


	<script src="/static/js/lg-jquery.min.js"></script>
	<script src="/static/js/lg-common.js"></script>
	<!--背景图片自动更换-->
	<script src="/static/js/lg-supersized.3.2.7.min.js"></script>
	<script src="/static/js/lg-supersized-init.js"></script>
	<!--表单验证-->
	<script src="/static/js/lg-jquery.validate.min.js?var1.14.0"></script>

</body>

</html>

myweb/myflask/templates/accounts/signin.html
<!doctype html>
<html lang="en">

<head>
	<!-- meta data -->
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->

	<!--font-family-->
	<!-- <link
		href="https://fonts.googleapis.com/css?family=Poppins:100,200,300,400,500,600,700,800,900&amp;subset=devanagari,latin-ext"
		rel="stylesheet"> -->
		<link
		href="https://fonts.css.network/css?family=Poppins:100,200,300,400,500,600,700,800,900&amp;subset=devanagari,latin-ext"
		rel="stylesheet">

	<!-- title of site -->
	<title>Sign in</title>

	<!-- For favicon png -->
	<link rel="shortcut icon" type="image/icon" href="/static/accounts/logo/favicon.png" />

	<!--font-awesome.min.css-->
	<link rel="stylesheet" href="/static/accounts/css/font-awesome.min.css">

	<!--animate.css-->
	<link rel="stylesheet" href="/static/accounts/css/animate.css">

	<!--bootstrap.min.css-->
	<link rel="stylesheet" href="/static/accounts/css/bootstrap.min.css">

	<!-- bootsnav -->
	<link rel="stylesheet" href="/static/accounts/css/bootsnav.css">

	<!--style.css-->
	<link rel="stylesheet" href="/static/accounts/css/style.css">

	<!--responsive.css-->
	<link rel="stylesheet" href="/static/accounts/css/responsive.css">

	<!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
	<!-- WARNING: Respond.js doesn't work if you view the page via file:// -->

	<!--[if lt IE 9]>
			<script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
			<script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
        <![endif]-->

</head>

<body>
	<!--[if lte IE 9]>
            <p class="browserupgrade">You are using an <strong>outdated</strong> browser. Please <a href="https://browsehappy.com/">upgrade your browser</a> to improve your experience and security.</p>
        <![endif]-->

	<!-- signin end -->
	<section class="signin">
		<div class="container">

			<div class="sign-content">
				<h2>sign in</h2>

				<div class="row">
					<div class="col-sm-12">
						<div class="signin-form">
							<form action="" method="POST">
								<div class="form-group">
									<label for="signin_form">Email</label>
									<input type="text" class="form-control" id="signin_form" name="username"
										placeholder="enter your email here">
								</div>
								<!--/.form-group -->
								<div class="form-group">
									<label for="signin_form">password</label>
									<input type="password" name="password" class="form-control" id="signin_form"
										placeholder="Password">

									<div class="row">
										<div class="col-sm-12">
											<div class="signin-password">
												<div class="awesome-checkbox-list">
													<ul class="unstyled centered">

														<li>
															<input class="styled-checkbox" id="styled-checkbox-2"
																type="checkbox" value="value2">
															<label for="styled-checkbox-2">remember password</label>
														</li>

														<li>
															<a href="#">Forgot email or password ?</a>
														</li>

													</ul>
												</div>
												<!--/.awesome-checkbox-list -->
											</div>
											<!--/.signin-password -->
										</div>
										<!--/.col -->
									</div>
									<!--/.row -->

									<div class="row">
										<div class="col-sm-12">
											<div class="signin-footer">
												<button type="submit" class="btn signin_btn" data-toggle="modal"
													data-target=".signin_modal">
													sign in
												</button>
												{% with message = get_flashed_messages() %}
												<div style="text-align: center;">{{ message[0] }}</div>
												{% endwith %}
												<p>
													Don’t have an Account ?
													<a href="{{ url_for('accounts.register') }}">register</a>
												</p>
											</div>
											<!--/.signin-footer -->
										</div>
										<!--/.col-->
									</div>
									<!--/.row -->

								</div>
								<!--/.sign-content -->

							</form>
							<!--/form -->
							<!-- modal part start -->
						</div>
						<!--/.form-group -->
					</div>
					<!--/.signin-form -->
				</div>
				<!--/.col -->
			</div>
			<!--/.row -->
		</div>
		<!-- /.container -->
	</section>
	<!--/.signin -->

	<!-- signin end -->

	<!--footer copyright start -->
	<footer class="footer-copyright">
		<div id="scroll-Top">
			<i class="fa fa-angle-double-up return-to-top" id="scroll-top" data-toggle="tooltip" data-placement="top"
				title="" data-original-title="Back to Top" aria-hidden="true"></i>
		</div>
		<!--/.scroll-Top-->

	</footer>
	<!--/.hm-footer-copyright-->
	<!--footer copyright  end -->


	<!-- Include all js compiled plugins (below), or include individual files as needed -->

	<script src="/static/accounts/js/jquery.js"></script>

	<!--modernizr.min.js-->
	<!-- <script src="https://cdnjs.cloudflare.com/ajax/libs/modernizr/2.8.3/modernizr.min.js"></script> -->
	<script src="https://cdn.bootcss.com/modernizr/2.8.3/modernizr.min.js"></script>

	<!--bootstrap.min.js-->
	<script src="/static/accounts/js/bootstrap.min.js"></script>

	<!-- bootsnav js -->
	<script src="/static/accounts/js/bootsnav.js"></script>

	<!-- jquery.sticky.js -->
	<script src="/static/accounts/js/jquery.sticky.js"></script>
	<!-- <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-easing/1.4.1/jquery.easing.min.js"></script> -->
	<script src="https://cdn.bootcss.com/jquery-easing/1.4.1/jquery.easing.min.js"></script>


	<!--Custom JS-->
	<script src="/static/accounts/js/custom.js"></script>

</body>

</html>