myweb/myflask/main/urls.py
#!/usr/bin/env python3
#-*- coding: utf-8 -*-
"""
路由
"""

from flask import Blueprint, g

from . import views

main = Blueprint('main', __name__)

main.add_url_rule("/", "index", views.index)
main.add_url_rule("/sms_table", "sms", view_func=views.all_data)
main.add_url_rule('/hello/<username>', "hello", view_func=views.hello, methods=['POST', 'GET'])
main.add_url_rule('/hello', view_func=views.hello, methods=['POST', 'GET'])
main.add_url_rule('/test1', "test1", views.test1)
# main.add_url_rule('/login', view_func=views.login, methods=['GET', "POST"])
############ cur post 请求格式
# 传 json  {'mobile': ""， "content" : "**$$**$$***$$***$$***"}
# curl -i -H "Content-Type: application/json" -X POST -d '{"mobile" : "19994411399", "content" : "13.231.45.60$$Geth-test02$$erc20API$$2019-10-15 12:55:12$$出错重启了一次"}' http://localhost:5000/monitor/sms
main.add_url_rule('/monitor/sms', "sms_send", views.send_sms, methods=['POST'])

main.add_url_rule('/back/server_info', view_func=views.server_info)
main.add_url_rule('/back/home', view_func=views.back_home)
main.add_url_rule('/back/server_add', view_func=views.server_add, methods=['GET', 'POST'])

main.add_url_rule('/post', "post_test", views.post_test, methods=['POST', 'GET'])

# main.before_app_request(views.before_app_request)
# # main.after_app_request(views.after_app_requst)

myweb/myflask/main/views.py
#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""

"""
# 数据库模型
from .models import M_SMS
# 短信发送
from .sms_notice import SMS
import time
from flask import jsonify, request, abort, render_template, flash, redirect, url_for, session, current_app
from flask_login import current_user, login_required
import logging
import json


logger = logging.getLogger(__name__)

# @login_required
def all_data():
    """查询所有数据"""
    logger.info('%s', request.url)
    data = M_SMS.query.all()
    # return render_template("all_data.html", data=data)
    # 所有数据以json格式返回
    datas = []
    for d in data:
        if d.status == 0:
            d.status = "失败"
        else:
            d.status = "成功"
        datas.append({
            'id': d.id,
            'ip_addr': d.ip_addr,
            'sms_info': d.sms_info,
            're_mobile': d.re_mobile,
            "status": d.status,
            # 格式化输出时间
            'send_time': time.strftime("%Y-%m-%d %H:%M:%S", time.localtime(d.send_time)),
            'fail_info': d.fail_info
        })
    # return jsonify(data=datas)
    return render_template("show_all.html", data=datas)


def add_data(ip_addr, sms_info, re_mobile, status, fail_info=''):
    """添加一条数据"""
    # 测试数据
    # ip_addr = '2.2.4.8'
    # sms_info = "2019年9月30号测试了一条222"
    # re_mobile = "19994411399"
    # status = '0'
    # send_time = int(time.time())  # 系统当前时间戳
    sms = M_SMS(
        ip_addr=ip_addr,
        sms_info=sms_info,
        re_mobile=re_mobile,
        status=status,
        send_time=int(time.time()),  # 系统当前时间戳
        fail_info=fail_info
    )
    from app import db
    try:
        db.session.add(sms)
        db.session.commit()
    except Exception as e:
        current_app.logger.error('%s', e)
        db.session.rollback()
        db.session.flush()
        result = {'msg': '添加失败'}
        return jsonify(data=result)

    # data = M_SMS.query.filter_by(id=id).first()  # 返回结果中的第一个
    # ########## 添加成功后返回添加的数据
    # result = {
    #     'id' : sms.id,
    #     'ip_addr' : sms.ip_addr,
    #     'sms_info' : sms.sms_info,
    #     're_mobile' : sms.re_mobile,
    #     'status' : sms.status,
    #     'send_time' : sms.send_time
    # }
    # return jsonify(data=result)
    return jsonify(data={'msg': "成功添加到数据库"})


def send_sms():
    """ 发送短信通知 """
    if not request.json:
        abort(400)
    # print("type: ", type(request.json))
    # print(request.json)
    sms = SMS()
    # 接收参数
    result = request.json
    # 手机号
    sms.mobile = result['mobile'] or '19994411399'
    # 发送模板变量内容
    sms.content = result['content']
    # 发送警告
    send = sms.send()
    # 写入库
    content_list = result['content'].split("$$")  # 信息主要内容格式化为 list
    sms_info = "服务器{0[0]}（{0[1]}）的{0[2]}在{0[3]}发生错误：{0[4]}".format(
        content_list)
    if send['code'] == '0':  # 短信接口返回的状态码，0是成功，非0是失败
        add_data(
            ip_addr=content_list[0], sms_info=sms_info, re_mobile=sms.mobile, status=1)
    else:
        add_data(ip_addr=content_list[0], sms_info=sms_info,
                 re_mobile=sms.mobile, status=0, fail_info=send["msg"])
    # return json.dumps(request.json)
    # 返回发送结果
    return send


def hello(username="kk"):
    return "Hello %s !!" % username


def test1():
    return "test1"


def server_info(data='123'):
    return render_template("server_info.html", data=data)

def server_add():
    if request.method == 'POST':
        print("=======>>>", request.form, "长度： ", request.from_values())
        if request.form:
            # flash('Record was successfully added')
            return render_template('server_add.html', data=request.form)

    return render_template('server_add.html')
    # return render_template("info_add.html")

# 后台主页
@login_required
def back_home():
    return render_template("home.html")

# 主页
def index():
    return render_template("index.html")

# 测试post
def post_test():
    if request.method == 'POST':
        print("##############################")
        result = json.loads(request.data)
        print(type(result), "\n", result)
        # print(result)
        
        return jsonify("成功")

        
        # print("======>>>>",type(result))
        # result = eval(result)
        # print(type(result), "========>", result)
        
    return render_template("tables.html")

# 响应请求前的操作
def before_app_request():
    print(">>>", request.url)

# 响应请求后的操作 
def after_app_requst(response):
    print("<<<<", response.status)
    return response  # 必须返回一个值，否则会报错

myweb/myflask/templates/base-nav.html
<!doctype html>
<html lang="zh-CN">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    {% block meta %}

    {% endblock %}
    <link rel="icon" href="../../../../favicon.ico">
    <title>{% block title %}全屏效果-基于Bootstrap{% endblock %}</title>
    <!-- Bootstrap 核心CSS -->
    <link rel="stylesheet" href="https://code.z01.com/v4/dist/css/bootstrap.min.css">
    <style>
        /* * Globals */
        /* Links */
        a,
        a:focus,
        a:hover {
            color: #fff;
        }

        /* Custom default button */
        .btn-secondary,
        .btn-secondary:hover,
        .btn-secondary:focus {
            color: #333;
            text-shadow: none;
            /* Prevent inheritance from `body` */
            background-color: #fff;
            border: .05rem solid #fff;
        }

        /* * Base structure */
        html,
        body {
            height: 100%;
            background-color: #333;
        }

        body {
            color: #fff;
            text-align: center;
            text-shadow: 0 .05rem .1rem rgba(0, 0, 0, .5);
        }

        /* Extra markup and styles for table-esque vertical and horizontal centering */
        .site-wrapper {
            display: table;
            width: 100%;
            height: 100%;
            /* For at least Firefox */
            min-height: 100%;
            box-shadow: inset 0 0 5rem rgba(0, 0, 0, .5);
        }

        .site-wrapper-inner {
            display: table-cell;
            vertical-align: top;
        }

        .cover-container {
            margin-right: auto;
            margin-left: auto;
        }

        /* Padding for spacing */
        .inner {
            padding: 2rem;
        }

        /* * Header */
        .masthead {
            margin-bottom: 2rem;
        }

        .masthead-brand {
            margin-bottom: 0;
        }

        .nav-masthead .nav-link {
            padding: .25rem 0;
            font-weight: 700;
            color: rgba(255, 255, 255, .5);
            background-color: transparent;
            border-bottom: .25rem solid transparent;
        }

        .nav-masthead .nav-link:hover,
        .nav-masthead .nav-link:focus {
            border-bottom-color: rgba(255, 255, 255, .25);
        }

        .nav-masthead .nav-link+.nav-link {
            margin-left: 1rem;
        }

        .nav-masthead .active {
            color: #fff;
            border-bottom-color: #fff;
        }

        @media (min-width: 48em) {
            .masthead-brand {
                float: left;
            }

            .nav-masthead {
                float: right;
            }
        }

        /* * Cover */
        .cover {
            padding: 0 1.5rem;
        }

        .cover .btn-lg {
            padding: .75rem 1.25rem;
            font-weight: 700;
        }

        /* * Footer */
        .mastfoot {
            color: rgba(255, 255, 255, .5);
        }

        /* * Affix and center */
        @media (min-width: 40em) {

            /* Pull out the header and footer */
            .masthead {
                position: fixed;
                top: 0;
            }

            .mastfoot {
                position: fixed;
                bottom: 0;
            }

            /* Start the vertical centering */
            .site-wrapper-inner {
                vertical-align: middle;
            }

            /* Handle the widths */
            .masthead,
            .mastfoot,
            .cover-container {
                width: 100%;
                /* Must be percentage or pixels for horizontal alignment */
            }
        }

        @media (min-width: 62em) {

            .masthead,
            .mastfoot,
            .cover-container {
                width: 42rem;
            }
        }
    </style>
</head>

<body>
    {% block body %}
    <div class="site-wrapper">
        <div class="site-wrapper-inner">
            <div class="cover-container">
                <header class="masthead clearfix">
                    <div class="inner active">
                        <h3 class="masthead-brand">Cover</h3>
                        <nav class="nav nav-masthead"> <a class="nav-link active" href="#">Home</a> <a class="nav-link"
                                href="#">Features</a> <a class="nav-link" href="#">Contact</a> </nav>
                    </div>
                </header>
                <main role="main" class="inner cover">
                    <h1 class="cover-heading">全屏页面效果</h1>
                    <p class="lead">Cover is a one-page template for building simple and beautiful home pages. Download,
                        edit the text, and add your own fullscreen background photo to make it your own.</p>
                    <p class="lead"> <a href="#" class="btn btn-lg btn-secondary">Learn more</a> </p>
                </main>
                <footer class="mastfoot">
                    <div class="inner">
                        <p>Cover template for <a href="https://getbootstrap.com/">Bootstrap</a>, by <a
                                href="https://twitter.com/mdo">@mdo</a>.</p>
                    </div>
                </footer>
            </div>
        </div>
    </div>

    {% endblock %}
    <!-- Bootstrap 核心 JavaScript -->
    <script src="https://code.z01.com/js/jquery-3.2.1.slim.min.js"></script>
    <script src="https://code.z01.com/v4/dist/js/popper.min.js"></script>
    <script src="https://code.z01.com/v4/dist/js/bootstrap.min.js"></script>
</body>

</html>

myweb/myflask/templates/base-simple-nav.html
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
<title>{% block title %}简单web导航栏{% endblock %}</title>
<style type="text/css">
	/*设置整体*/
	*{
		padding: 0;
		margin: 0;
		font-family: "微软雅黑";	
	}
	/*设置header的div区*/
	.header{
		height: 72px ;
    	background: #458fce ;
	}
	/*设置logo的div区*/
	.header .logo{
		color: #fff ;
		font-size: 30px ;
		font-weight:500 ;
    	line-height: 72px ;
    	margin-left: 20px ;
    	display:inline-block ;
    	float: left ;/*左浮动*/
	}
	/*设置li标签里*/
	.header ul li{
		float: left ;
		color: #fff ;
    	display: inline-block ;
    	width: 112px ;
    	height: 72px ; 
    	text-align: center ;
    	line-height:72px ;
    	/*cursor: pointer ;光标显示成小手型*/
	}
	/*细节调整*/
	ul li{
		list-style: none ;/*li的小圆点去掉*/
	}
	.header ul li.first.bak{
		margin-left: 30px ;/*设置“首页”与“原创文字”间距*/
    	background:#74b0e2 ;/*“首页”设置默认背景*/
	}
	
	/*设置a链接标签*/
	a{
		color: #fff ;
    	text-decoration: none ;
        font-size: 24px;
	}
	/*设置导航添加hover事件*/
	.header ul li:hover{
		 background:#74b0e2 ;
	}
	/*设置登录、注册按钮*/
	.header .login{
		float: right ; 
    	color: #fff ;
    	line-height: 72px ;
    	margin-right: 20px ;
	}
    .active{
        background:#74b0e2 ;
    }
</style>
</head>
<body>
	<div class="header">
		<div class='logo'>导航栏</div>
		<ul>
			<li class="active"><a href="{{ url_for('main.index') }}">首页</a></li>
			<li><a href="{{ url_for('main.back_home') }}">原创</a></li>
			<li><a href="#">转载</a></li>
		</ul>
		<div class="login">
		<span><a href="javascript:void(0)">登陆</a></span>  
    	<span>|</span> 
    	<span><a href="javascript:void(0)">注册</a></span>
		</div>
    </div>
    <div>
    <p>{% block pagecontent %}
            网页的中间内容部分写在当前的位置
            {% endblock %}</p>
</div>
<script>
        $(function () {
            $("ur>li").find("li").each(function () {
                var a = $(this).find("a")[0];
                if ($(a).attr("href") === location.pathname) {
                    $(this).addClass("active");
                } else {
                    $(this).removeClass("active");
                }
            });
        })
    </script>
</body>
</html>

myweb/myflask/templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">

    {% block meta %}

    {% endblock %}
    <title>{% block title%}首页{% endblock %}</title>

    <link href="/static/css/bootstrap.min.css" rel="stylesheet">
    <script src="/static/js/jquery.min.js"></script>
    <script src="/static/js/bootstrap.min.js"></script>
    <!-- 点击下拉改为悬停下拉 -->
    <script src="/static/js/bootstrap-hover-dropdown.min.js"></script>
    {% block style %}

    {% endblock %}
</head>

<body>

    <header>
        <nav class="navbar navbar-default navbar-inverse" role="navigation">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse"
                    data-target="#bs-example-navbar-collapse-1"> <span class="sr-only">Toggle navigation</span><span
                        class="icon-bar"></span><span class="icon-bar"></span><span class="icon-bar"></span></button> <a
                    class="navbar-brand" href="#">Brand</a>
            </div>

            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav">
                    <li class="active">
                        <a href="{{ url_for('main.index') }}">首页</a>
                    </li>
                    <li>
                        <a href="{{ url_for('main.sms') }}">短信记录</a>
                    </li>
                    <!-- <li class="disabled"> /* 灰色不可点击 */ -->
                    <li>
                        <a href="{{ url_for('main.post_test') }}">信息</a>
                    </li>
                    <li class="dropdown">
                        <a href="#" data-toggle="dropdown" data-hover="dropdown" class="dropdown-toggle">下拉<strong
                                class="caret"></strong></a>
                        <ul class="dropdown-menu">
                            <li>
                                <a href="#">操作</a>
                            </li>
                            <li>
                                <a href="#">设置栏目</a>
                            </li>
                            <li>
                                <a href="#">更多设置</a>
                            </li>
                            <li class="divider">
                            </li>
                            <li>
                                <a href="#">分割线</a>
                            </li>
                        </ul>
                    </li>
                </ul>
                <!-- 搜索框 -->
                <form class="navbar-form navbar-left" role="search">
                    <div class="form-group">
                        <input type="text" class="form-control" />
                    </div> <button type="submit" class="btn btn-default">Submit</button>
                </form>
                <ul class="nav navbar-nav navbar-right">
                    <li>
                        {% if current_user.is_authenticated %}
                        <a href="{{ url_for('accounts.logout') }}">{{ current_user.get_id() }}注销</a>
                        {% else %}
                        <a href="{{ url_for('accounts.login') }}">登录</a>
                        {% endif %}
                    </li>
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">Dropdown<strong
                                class="caret"></strong></a>
                        <ul class="dropdown-menu">
                            <li>
                                <a href="#">Action</a>
                            </li>
                            <li>
                                <a href="#">Another action</a>
                            </li>
                            <li>
                                <a href="#">Something else here</a>
                            </li>
                            <li class="divider">
                            </li>
                            <li>
                                <a href="#">Separated link</a>
                            </li>
                        </ul>
                    </li>
                </ul>
            </div>
        </nav>
    </header>

    {% block pagecontent %}
    网页的中间内容部分写在当前的位置
    {% endblock %}



    <script>
        $(function () {
            $("div>ul").find("li").each(function () {
                var a = $(this).find("a")[0];
                if ($(a).attr("href") === location.pathname) {
                    $(this).addClass("active");
                } else {
                    $(this).removeClass("active");
                }
            });
        })
        $(function () {
            $("[data-toggle='tooltip']").tooltip();
        });
        $(function () {
            $(".tooltip-options a").tooltip({
                html: true
            });
        });
    </script>
</body>

</html>

myweb/myflask/templates/home.html
{% extends 'base.html' %}

{% block pagecontent %}
Hello {{ current_user.get_id() }}, 欢迎回来！！
            {% endblock %}

{% block body %}

<div class="site-wrapper">
    <div class="site-wrapper-inner">
        <div class="cover-container">
            <header class="masthead clearfix">
                <div class="inner">
                    <h3 class="masthead-brand">Cover</h3>
                    <nav class="nav nav-masthead"> <a class="nav-link active" href="#">Home</a> <a class="nav-link"
                            href="#">Features</a> <a class="nav-link" href="#">Contact</a> </nav>
                </div>
            </header>
            <main role="main" class="inner cover">
                <h1 class="cover-heading">Hello {{ current_user.get_id() }}, 欢迎回来！！</h1>
            </main>
            <footer class="mastfoot">
                <div class="inner">
                    <p>Cover template for <a href="https://getbootstrap.com/">Bootstrap</a>, by <a
                            href="https://twitter.com/mdo">@mdo</a>.</p>
                </div>
            </footer>
        </div>
    </div>
</div>
{% endblock %}

myweb/myflask/templates/index.html
{% extends 'base.html' %}

{% block title %}
MyFlask
{% endblock %}
{% block style %}
<style>
    .table tbody tr td {
        vertical-align: middle;
    }

    .table-bordered>thead>tr>td,
    .table-bordered>thead>tr>th {
        vertical-align: middle;
    }
</style>
{% endblock %}
{% block pagecontent %}
<script type="text/javascript">
    $(document).ready(function () {
        //上移
        $("input.upbtn").each(function () {
            $(this).click(function () {
                var $tr = $(this).parents("tr");
                if ($tr.index() != 0) {
                    $tr.prev().before($tr); //在每个匹配的元素之前插入内容。
                }
            });
        });
        //下移
        var trLength = $("input.downbtn").length;
        $("input.downbtn").each(function () {
            $(this).click(function () {
                var $tr = $(this).parents("tr");
                if ($tr.index() != trLength - 1) {
                    $tr.next().after($tr); //在每个匹配的元素之后插入内容。
                }
            });
        });
    });
</script>
<table>
    <tr>
        <td><input type="text" /></td>
        <td><input type="button" value="上移" class="upbtn" />
            <input type="button" value="下移" class="downbtn" />
        </td>
    </tr>
    <tr>
        <td>5</td>
        <td><input type="button" value="上移" class="upbtn" />
            <input type="button" value="下移" class="downbtn" />
        </td>
    </tr>
    <tr>
        <td>6</td>
        <td><input type="button" value="上移" class="upbtn" />
            <input type="button" value="下移" class="downbtn" />
        </td>
    </tr>
    <tr>
        <td>6</td>
        <td><input type="button" value="上移" class="upbtn" />
            <input type="button" value="下移" class="downbtn" />
        </td>
    </tr>
</table>
<div style="margin: 15px 15px 15px 15px;">

    <p>Index</p>

    <div class="form-group">
        <select class="selectpicker">
            <option>A</option>
            <option>B</option>
            <option>C</option>
        </select>
    </div>

    <button type="button" class="btn btn-primary" onclick="alter(this.closest('div'))">123</button>
    <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#info">
        Launch demo modal
    </button>

    <!-- infoModal -->
    <div class="modal fade" id="info" tabindex="-1" role="dialog" aria-labelledby="infoTitle" aria-hidden="true"
        data-backdrop="static" data-keyboard="false">
        <div class="modal-dialog" role="document" style="min-width: 800px;">
            <div class="modal-content">
                <div class="modal-header">
                    <ul class="nav nav-pills navbar-right">
                        <li class="active"><a href="#infoIP" data-toggle="tab">IP地址</a></li>
                        <li><a href="#infoID" data-toggle="tab">远程桌面</a></li>
                        <li><a href="#infoOther" data-toggle="tab">其它</a></li>

                    </ul>
                </div>
                <div class="modal-body">
                    <div class="tab-content">
                        <div class="tab-pane fade in active" id="infoIP">
                            <table class="table table-bordered" style="text-align: center;">
                                <thead>
                                    <tr>
                                        <td>
                                            公网IP
                                        </td>
                                        <td>
                                            内网IP
                                        </td>
                                        <td>
                                            远程web密码
                                        </td>
                                        <td style="width: 150px;">
                                            <button type="button" class="btn btn-warning"
                                                onclick="add_line(this);">增加行</button>
                                        </td>
                                    </tr>
                                </thead>
                                <tbody id="content">
                                </tbody>
                            </table>
                        </div>

                        <div class="tab-pane fade" id="infoID">
                            <table class="table table-bordered" style="text-align: center;">
                                <thead>
                                    <tr>
                                        <td>
                                            用户名
                                        </td>
                                        <td>
                                            密码
                                        </td>
                                        <td>
                                            端口号
                                        </td>
                                        <td style="width: 150px;">
                                            <button type="button" class="btn btn-warning "
                                                onclick="add_line(this);">增加行</button>
                                        </td>
                                    </tr>
                                </thead>
                                <tbody id="content">
                                </tbody>
                            </table>

                        </div>

                        <div class="tab-pane fade" id="infoOther">
                            <table class="table table-bordered" style="text-align: center;">
                                <thead>
                                    <tr>
                                        <td>
                                            名称
                                        </td>
                                        <td>
                                            值1
                                        </td>
                                        <td>
                                            值2
                                        </td>
                                        <td>
                                            值3
                                        </td>
                                        <td>
                                            值4
                                        </td>
                                        <td style="width: 150px;">
                                            <button type="button" class="btn btn-warning "
                                                onclick="add_line(this);">增加行</button>
                                        </td>
                                    </tr>
                                </thead>
                                <tbody id="content">
                                </tbody>
                            </table>

                        </div>
                    </div>
                </div>

                <div class="modal-footer text-center">
                    <!-- <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button> -->
                    <button id="submit" type="button" class="btn btn-primary" onclick="SubData()"
                        data-dismiss="modal">Save
                        changes</button>
                </div>
            </div>
        </div>
    </div>

</div>
<script type="text/javascript" src="/static/js/jquery.color.min.js"></script>
<script type="text/javascript" src="/static/js/jquery.color.plus-names.min.js"></script>
<script type="text/javascript" src="/static/js/info_add.js"></script>
{% endblock %}

myweb/myflask/templates/info_add.html
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>

<head>
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
  <title>动态添加行删除行</title>
  <style>
    * {
      margin: 0;
      padding: 0;
    }

    ul {
      list-style: none;
    }

    td {
      contenteditable: true;
    }

    .box {
      width: 900px;
      margin: 50px auto;
    }

    .box table {
      width: 100%;
      text-align: center;
    }

    .box table td {
      height: 50px;
    }

    .tianjia {
      width: 40px;
      height: 20px;
      cursor: pointer;
    }

    .shanchu {
      width: 40px;
      height: 20px;
      cursor: pointer;
    }
  </style>
  <!-- <script type="text/javascript" src="jquery-1.7.2.min.js"></script> -->
  <!-- jQuery文件。务必在bootstrap.min.js 之前引入 -->
  <script src="https://cdn.staticfile.org/jquery/2.1.1/jquery.min.js"></script>
  <script type="text/javascript">
    $(function () {
      $('.tianjia').click(function (e) {
        var $html = $(
          "<tr><td><input type='text' class='input_140'   placeholder='请输入姓名'/></td><td><input type='text' class='input_140'   placeholder='请输入姓名'/></td><td><input type='text' class='input_140'   placeholder='请输入姓名'/></td><td><input type='text' class='input_140'   placeholder='请输入姓名'/></td><td><a class='shanchu' onclick=\'sc()\'>删除</a></td></tr>"
        );
        $('.box table ').append($html);
      });

    })

    function sc() {
      $(" .box table tr").eq($(this).index()).remove();
    }
  </script>
</head>

<body>
  <div class="box">
    <form action="" method="post">
      <table cellpadding="1" cellspacing="0" border="0">
        <tr>
          <th width="16%">名称</th>
          <th width="29%">用户名/值1</th>
          <th width="20%">密码/值2</th>
          <th width="15%">备注/值3</th>
          <th width="20%">删除</th>
        </tr>
        <tr class="di">
          <td><input type='text' class='input_140' placeholder='请输入姓名' /></td>
          <td><input type='text' class='input_140' placeholder='请输入姓名' /></td>
          <td><input type='text' class='input_140' placeholder='请输入姓名' /></td>
          <td><input type='text' class='input_140' placeholder='请输入姓名' /></td>
          <td><a class="shanchu ">删除</a></td>
        </tr>
        <!--默认可删除-->
      </table>
      <div class="tianjia">添加</div>
      <button id="submit" type="submit">提交</button>
    </form>
  </div>

</body>

</html>

myweb/myflask/templates/server_info.html
<!DOCTYPE html>
<html>
    <h3>Server Add (<a href = "{{ url_for('.server_add') }}">Add Server
    </a>)</h3>
    <p>{{ data }}</p>
</html>

myweb/myflask/templates/show_all.html
{% extends "base.html" %}

{% block title %}业务警告通知{% endblock %}
{% block style %}
<link rel="stylesheet" type="text/css" href="static/css/show_all.css">{% endblock %}

{% block pagecontent %}
<!-- <h2>调整浏览器窗口大小查看效果</h2> -->
<img src="{{ url_for('static', filename='images/360safe.png')}}" alt="你的图片被外星人劫持了～～" />
<div class="table-wrapper">
    <table class="fl-table">
        <thead>
            <tr>
                <th id="w5">ID</th>
                <th id="w10">IP</th>
                <th id="w45">短信内容</th>
                <th id="w10">接收手机号</th>
                <th id="w5">状态</th>
                <th id="w15">发送时间</th>
            </tr>
        </thead>
        <tbody>
            {% for d in data %}
            <tr>
                <td>{{ d.id }}</td>
                <td>{{ d.ip_addr }}</td>
                <td class="sms_info">{{ d.sms_info }}</td>
                <td>{{ d.re_mobile }}</td>
                {% if d.status=='失败' %}
                <td><a href="#" data-toggle="tooltip" title="{{ d.fail_info }}"
                        style="color: #FF0000;">{{ d.status }}</a>
                </td>
                {% else %}
                <td>{{ d.status }}</td>
                {% endif %}
                <td>{{ d.send_time }}</td>
            </tr>
            {% endfor %}
        <tbody>
    </table>
</div>
{% endblock %}